# Generated by Django 5.0.14 on 2026-09-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fide_id', models.CharField(blank=True, max_length=30, null=True)),
                ('national_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(choices=[('NONE', 'No Title'), ('GM', 'Grandmaster (GM)'), ('WGM', 'Woman Grandmaster (WGM)'), ('IM', 'International Master (IM)'), ('WIM', 'Woman International Master (WIM)'), ('FM', 'FIDE Master (FM)'), ('WFM', 'Woman FIDE Master (WFM)'), ('CM', 'Candidate Master (CM)'), ('WCM', 'Woman Candidate Master (WCM)')], default='NONE', max_length=10)),
                ('rating', models.PositiveIntegerField(default=1200, help_text='FIDE / Standard Rating')),
                ('national_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('federation', models.CharField(default='IND', help_text='3-letter IOC/FIDE country code, e.g. IND, USA, NOR, IND', max_length=10)),
                ('club_or_city', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 15th International Grandmaster Open 2026', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tournament_code', models.CharField(blank=True, help_text='Reference Code like tnr1263143', max_length=50, unique=True)),
                ('tournament_system', models.CharField(choices=[('SWISS', 'Swiss-System'), ('ROUND_ROBIN', 'Round Robin')], default='SWISS', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Registration Open'), ('ACTIVE', 'In Progress'), ('FINISHED', 'Tournament Completed')], default='UPCOMING', max_length=20)),
                ('time_control_type', models.CharField(choices=[('CLASSICAL', 'Classical'), ('RAPID', 'Rapid'), ('BLITZ', 'Blitz'), ('BULLET', 'Bullet'), ('STANDARD', 'Standard')], default='CLASSICAL', max_length=20)),
                ('time_control', models.CharField(default='90 min + 30 sec / move', help_text='Time control description', max_length=150)),
                ('rounds_count', models.PositiveIntegerField(default=7, help_text='Number of rounds')),
                ('current_round_num', models.PositiveIntegerField(default=0)),
                ('federation', models.CharField(default='FIDE', help_text='e.g. FIDE, IND, USA, GER', max_length=50)),
                ('city', models.CharField(default='International Arena', max_length=100)),
                ('venue', models.CharField(default='Grand Conference Hall', max_length=200)),
                ('chief_arbiter', models.CharField(default='IA John Smith (FIDE)', max_length=100)),
                ('deputy_arbiter', models.CharField(blank=True, default='FA Sarah Jenkins', max_length=100)),
                ('organizer', models.CharField(default='Chess Federation Organization', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, default='Official FIDE rated chess tournament with standard Swiss pairing system.')),
                ('rules_and_prizes', models.TextField(blank=True, default='Tie-Break 1: Buchholz Cut 1\nTie-Break 2: Buchholz\nTie-Break 3: Sonneborn-Berger\nTie-Break 4: Direct Encounter')),
                ('is_rated', models.BooleanField(default=True, help_text='Official Rated Tournament')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('is_paired', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('tournament', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_rank', models.PositiveIntegerField(default=1)),
                ('current_points', models.FloatField(default=0.0)),
                ('buchholz', models.FloatField(default=0.0)),
                ('buchholz_cut1', models.FloatField(default=0.0)),
                ('sonneborn_berger', models.FloatField(default=0.0)),
                ('direct_encounter', models.FloatField(default=0.0)),
                ('wins_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Active in ongoing rounds')),
                ('received_bye', models.BooleanField(default=False, help_text='Has received a pairing Bye in this tournament')),
                ('color_streak', models.IntegerField(default=0, help_text='Consecutive same colors (+ve for White, -ve for Black)')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='tournaments.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['starting_rank'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(choices=[('*', '* (Unfinished / In Progress)'), ('1-0', '1 - 0 (White wins)'), ('0-1', '0 - 1 (Black wins)'), ('1/2-1/2', '½ - ½ (Draw)'), ('1-0_FF', '1 - 0 [FF] (White win by forfeit)'), ('0-1_FF', '0 - 1 [FF] (Black win by forfeit)'), ('0-0_FF', '0 - 0 [FF] (Double forfeit)'), ('1-0_BYE', '1 - 0 [BYE] (Full Point Bye)'), ('1/2-1/2_BYE', '½ - ½ [BYE] (Half Point Bye)'), ('0-0_BYE', '0 - 0 [BYE] (Zero Point Bye)')], default='*', max_length=20)),
                ('white_score', models.FloatField(blank=True, null=True)),
                ('black_score', models.FloatField(blank=True, null=True)),
                ('pgn', models.TextField(blank=True, help_text='PGN Moves or commentary')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round')),
                ('black_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_matches', to='tournaments.tournamentparticipant')),
                ('white_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_matches', to='tournaments.tournamentparticipant')),
            ],
            options={
                'ordering': ['board_number'],
                'unique_together': {('round', 'board_number')},
            },
        ),
    ]
