# Generated by Django 5.0.14 on 2026-09-26 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANISER', 'Tournament Organiser / Arbiter'), ('PLAYER', 'Chess Player')], default='PLAYER', max_length=20)),
                ('organization_name', models.CharField(blank=True, default='', help_text='e.g. Chess Federation / Academy', max_length=150)),
                ('arbiter_title', models.CharField(blank=True, default='', help_text='e.g. IA (International Arbiter), FA, NA', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='tournaments.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
