# Generated by Django 5.0.14 on 2026-09-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_userprofile'),
    ]

    operations = [
    ]
