# Generated by Django 5.0.14 on 2026-09-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20260927_0155'),
    ]

    operations = [
    ]
